[package]
name = "refined"
version = "0.0.0"
edition = "2021"
description = "Simple refinement types; parse, don't validate!"
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.215", features = ["derive"], optional = true }
thiserror = "2.0.8"

[dev-dependencies]
serde_json = "1.0.133"

[features]
default = [ "serde" ]
implication = []
serde = [ "dep:serde" ]

[package.metadata.docs.rs]
all-features = true
