name: "Publish"
on:
  release:
    types: [released]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v27
      with:
        nix_path: nixpkgs=channel:nixos-24.11
    - uses: nicknovitski/nix-develop@v1
    - name: cargo login
      run: cargo login ${{ secrets.CRATES_IO_API_TOKEN }}
    - name: cargo publish
      run: cargo publish
